import type { Metadata } from "next";
import Link from "next/link";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { SourceCatalogListV12 } from "@/components/source-catalog-list-v12";
import { hadithCollections } from "@/data/hadith-collections";
import { hadithPublicProviders } from "@/data/hadith-provider-links";

export const metadata:Metadata={title:"Kaynaklar ve doğrulama yöntemi",description:"Kur’an ve hadis kaynaklarının, asli eserlerin ve teknik erişim sağlayıcılarının nasıl ayrıldığını inceleyin.",alternates:{canonical:"/kaynaklar"}};
const primaryHadithCollectionIds=new Set(["sahih-al-bukhari","sahih-muslim","sunan-abi-dawud","jami-at-tirmidhi"]);
const hadithWorks=hadithCollections.filter((item)=>primaryHadithCollectionIds.has(item.id));
const hadithWorkLabels:Record<string,string>={"sahih-al-bukhari":"Sahîh-i Buhârî","sahih-muslim":"Sahîh-i Müslim","sunan-abi-dawud":"Sünen-i Ebû Dâvûd","jami-at-tirmidhi":"Câmiu’t-Tirmizî"};
const providerDescriptions:Record<string,string>={"diyanet-hadislerle-islam":"Güvenilir Türkçe okuma ve bibliyografik erişim.","sunnah-com":"Arapça matn ve global hadis numarası erişimi.",dorar:"Kaynak, Arapça matn ve klasik değerlendirme izi için teknik çapraz kontrol."};

export default function SourcesPage(){return <main><Header/><section className="sourcesHero"><p className="topicKicker">ŞEFFAFLIK <span>·</span> YÖNTEM <span>·</span> KAYNAK</p><h1>Kaynakların yeri<br/>birbirine karışmasın.</h1><p>Asli eser, Türkçe okuma hizmeti ve teknik doğrulama sağlayıcısı aynı şey değildir. SohbetKaynağı bu ayrımı her yönlendirmede korur.</p></section><section className="methodBand"><div><span>01</span><h2>Referans doğrulanır</h2><p>Ayet adresi; hadis eseri, râvisi ve numara bilgisi kontrol edilir.</p></div><div><span>02</span><h2>Sağlayıcı ayrılır</h2><p>Teknik erişim sitesi, asli eser veya sıhhat otoritesi gibi sunulmaz.</p></div><div><span>03</span><h2>Kullanıcı kaynağa gider</h2><p>Site hüküm vermez; incelemeyi güvenilir dış kaynakta sürdürür.</p></div></section><section className="catalogSection quranCatalog"><div className="sectionHeading"><div><p>KUR’AN KAYNAKLARI</p><h2>Meal ve tefsir eserleri</h2></div><span>Her ayet için mevcut güvenilir yönlendirmeler.</span></div><SourceCatalogListV12/></section><section className="hadithWorksSection"><div className="sectionHeading"><div><p>HADİS · ASLİ ESERLER</p><h2>Hadis kataloğunun asli eserleri</h2></div><span>Sağlayıcı siteler değil, hadis kayıtlarının dayandığı bibliyografik eserler.</span></div><div className="hadithWorkGrid">{hadithWorks.map((work)=><article key={work.id}><span>ASLİ ESER</span><p className="arabicWork" lang="ar" dir="rtl">{work.arabicName}</p><h3>{hadithWorkLabels[work.id]??work.canonicalName}</h3><p>{work.author}</p><small>{work.notes}</small></article>)}</div></section><section className="providerSection"><div className="sectionHeading"><div><p>ERİŞİM VE TEKNİK DOĞRULAMA</p><h2>Sağlayıcılar</h2></div><span>Bu hizmetler asli hadis eserlerinin yerine geçmez.</span></div><div className="providerGrid">{hadithPublicProviders.map((provider)=><article key={provider.id}><span>{provider.role==="trusted_turkish_reading_provider"?"TÜRKÇE OKUMA":provider.role==="arabic_and_locator_provider"?"ARAPÇA VE NUMARA":"TEKNİK ÇAPRAZ KONTROL"}</span><h3>{provider.name}</h3><p>{providerDescriptions[provider.id]}</p><a href={provider.baseUrl} target="_blank" rel="noopener noreferrer">Siteyi aç <i aria-hidden="true">↗</i></a></article>)}</div></section><section className="releaseNote"><p>SohbetKaynağı araştırmaya başlangıç sunar. Fetva üretmez, kullanıcı adına dinî hüküm vermez ve teknik sağlayıcıları asli eser gibi göstermez.</p><Link href="/konular">Konu kataloğuna geçin <span aria-hidden="true">→</span></Link></section><Footer/></main>}
