import Link from "next/link";
import { Footer } from "@/components/footer";
import { Header } from "@/components/header";
import { SearchFormV12 } from "@/components/search-form-v12";
import { topicViews } from "@/lib/content";
import { getTopicInitial } from "@/lib/topic-initial";

export default function HomePage() {
  const featured = topicViews.slice(0, 12);
  return <main><Header/><section className="hero"><div className="heroPattern" aria-hidden="true"/><div className="heroInner"><p className="kicker"><span/> SOHBETKAYNAĞI · DOĞRULANMIŞ KAYNAK YÖNLENDİRMESİ</p><h1>Konuya göre Kur’an ve hadis <em>kaynaklarını bulun.</em></h1><p className="heroText">Doğrulanmış ayet ve hadis referansları üzerinden güvenilir kaynaklara ulaşın. Bir konu veya gündelik bir ifade yazarak başlayın.</p><SearchFormV12/><p className="searchHint">Örnek: Sabır, dua, kul hakkı veya “pişman oldum”</p></div><div className="heroFacts" aria-label="Katalog özeti"><div><strong>50</strong><span>konu başlığı</span></div><div><strong>135</strong><span>ayet ilişkisi</span></div><div><strong>50</strong><span>doğrulanmış hadis kaydı</span></div></div></section><section className="topicsSection" id="konular"><div className="sectionHeading"><div><p>KONU KATALOĞU</p><h2>Kaynaklara açılan başlıklar</h2></div><span>İbadetten insan ilişkilerine, 50 konu tek bir araştırma düzeninde.</span></div><div className="topicList">{featured.map((topic,index)=><Link href={`/konu/${topic.slug}`} className="topicRow" key={topic.slug}><span className="topicRowNo">{String(index+1).padStart(2,"0")}</span><span className={`topicRowGlyph ${topic.presentation.color}`} aria-hidden="true">{getTopicInitial(topic.title)}</span><span><small>{topic.presentation.eyebrow}</small><strong>{topic.title}</strong></span><i aria-hidden="true">→</i></Link>)}</div><Link href="/konular" className="methodLink">50 konunun tamamını keşfedin <span>→</span></Link></section><section className="methodology"><div><p>ŞEFFAF YÖNTEM</p><h2>Kaynakları nasıl hazırlıyoruz?</h2><p className="methodologyLead">Kullanıcı bir konu seçer; biz ayet ve hadis referanslarını asli kaynaklarıyla görünür kılarız.</p></div><ol><li><span>01</span><b>Konu bulunur.</b><small>Arama veya katalog üzerinden ilgili başlığa ulaşılır.</small></li><li><span>02</span><b>Ayet referansları kontrol edilir.</b><small>Meal ve tefsir okumaları güvenilir dış kaynaklara yönlendirilir.</small></li><li><span>03</span><b>Hadis kaydı doğrulanır.</b><small>Asli eser, râvi, hadis numarası ve sıhhat kaynağı ayrı ayrı incelenir.</small></li><li><span>04</span><b>Sağlayıcı ile eser ayrılır.</b><small>Diyanet Türkçe okuma; Sunnah.com metin ve numara erişimi; Dürer teknik çapraz kontrol sağlar. Bunların hiçbiri asli eserin yerine geçmez.</small></li></ol><p className="methodologyNote">SohbetKaynağı fetva üretmez. AI ile hazırlanmış hadis çalışma tercümeleri kullanıcıya sunulmaz.</p></section><Footer/></main>;
}
