import type { primaryHadithPublicPresentations } from "@/lib/hadith-public-presentation";
import styles from "./hadith-source-card.module.css";

type PublicHadith = (typeof primaryHadithPublicPresentations)[number];
const gradingLabels = { sahih:"Sahih", hasen:"Hasen", hasan_sahih:"Hasen sahih", daif:"Zayıf", mixed:"Farklı değerlendirmeler", not_applicable:"Uygulanamaz", unknown:"Belirtilmemiş" } as const;
const sourceWorkLabels:Record<string,string>={"sahih-al-bukhari":"Sahîh-i Buhârî","sahih-muslim":"Sahîh-i Müslim","sunan-abi-dawud":"Sünen-i Ebû Dâvûd","jami-at-tirmidhi":"Câmiu’t-Tirmizî"};

export function HadithSourceCard({ hadith }: { hadith: PublicHadith }) {
  const locatorLabel = hadith.primaryLocator.scheme === "collection_global" ? `Hadis ${hadith.primaryLocator.value}` : hadith.primaryLocator.value;
  const textType = hadith.arabicTextType === "excerpt" ? "İlgili bölüm" : "Tam metin";
  return <section className={styles.section} aria-labelledby="hadith-heading"><div className={styles.heading}><div><p>HADİS KAYNAĞI</p><h2 id="hadith-heading">Konuyla ilgili doğrulanmış hadis</h2></div><span>1 doğrulanmış kayıt</span></div><article className={styles.card}><div className={styles.index} aria-hidden="true">H</div><div className={styles.content}><div className={styles.topline}><span>ASLİ ESER</span><span className={styles.verified}>KAYNAĞI DOĞRULANDI</span></div><h3>{sourceWorkLabels[hadith.sourceWork.id]??hadith.sourceWork.title}</h3><p className={styles.locator}>{locatorLabel}</p><dl className={styles.facts}><div><dt>Râvi</dt><dd>{hadith.narrator}</dd></div><div><dt>Sıhhat</dt><dd>{gradingLabels[hadith.grading]}</dd></div><div><dt>Metin kapsamı</dt><dd>{textType}</dd></div></dl>
    <div className="hadithArabicBlock"><div className="hadithArabicHeader"><span>ARAPÇA HADİS METNİ</span>{hadith.arabicTextType === "excerpt" && <span className="hadithExcerptBadge">İlgili bölüm</span>}</div><p className="hadithArabicText" lang="ar" dir="rtl">{hadith.arabicText}</p></div>
    <div className={styles.actions}>{hadith.turkishReading && <a href={hadith.turkishReading.link.url} target={hadith.turkishReading.link.target} rel={hadith.turkishReading.link.rel} className={styles.primaryAction}>Türkçe oku <span aria-hidden="true">↗</span></a>}{hadith.sourceReading && <a href={hadith.sourceReading.link.url} target={hadith.sourceReading.link.target} rel={hadith.sourceReading.link.rel} className={styles.secondaryAction}>Kaynak kaydını aç <span aria-hidden="true">↗</span></a>}</div>
    <details className={styles.details}><summary>Kaynak ve doğrulama bilgisi</summary><div className={styles.detailBody}><dl><div><dt>Asli kaynak</dt><dd>{hadith.sourceReference}</dd></div><div><dt>Râvi</dt><dd>{hadith.narrator}</dd></div><div><dt>Sıhhat kaynağı</dt><dd>{hadith.gradingSource}</dd></div><div><dt>Arapça kayıt</dt><dd>{textType}</dd></div><div><dt>Teknik kontrol</dt><dd>{hadith.technicalProviders.map((provider) => provider.name).join(" · ")}</dd></div></dl><p>Teknik erişim sağlayıcıları asli hadis eseri veya bağımsız sıhhat otoritesi olarak sunulmaz.</p>{hadith.parallelTurkishResources.map((resource)=><a key={`${resource.providerId}-${resource.providerLocator}`} href={resource.link.url} target={resource.link.target} rel={resource.link.rel}>İlgili rivayeti Diyanet’te incele <span aria-hidden="true">↗</span></a>)}</div></details>
  </div></article></section>;
}
