import { sourceLinks,sourceProviderById,sourceWorkById,sourceWorks } from "@/data/source-catalog";
import { getGlobalAyahNumber,surahMetadataByNumber } from "@/data/surah-metadata";
import type { BuiltSourceGroup,BuiltSourceLink,SourceContentType,SourceLink } from "@/domain/content-types";
export type BuildSourceLinkInput={sourceId:string;contentType:SourceContentType;surahNumber:number;surahName?:string;surahSlug?:string;ayahStart:number;ayahEnd?:number};
const labels:Record<SourceContentType,string>={meal:"Meali aç",tafsir:"Tefsiri incele",quran:"Kur’an Portalında aç",reference:"Kaynağı aç"};
const kuranMealiSlugOverrides:Record<number,string>={3:"ali-imran"};
const tahaviThirtyVerseSections=new Set([3,4,5,7,8,9,10,11,12,15,16,17,18,21,26,27,28,30,33,34,36,37,38,39,40,41,43,44,51,55,56]);
const tahaviExplicitSections:Record<number,Array<[number,number]>>={
  2:[[1,29],[30,59],[60,89],[90,119],[120,149],[150,179],[180,209],[210,239],[240,269],[270,286]],
  6:[[1,30],[31,60],[61,90],[91,120],[121,165]],
  25:[[1,30],[31,77]],
  29:[[1,30],[31,69]],
};
function tahaviTarget(surahNumber:number,surahSlug:string,ayah:number){const surahUrl=`https://www.tahavi.com/${surahSlug}-suresi/`;const metadata=surahMetadataByNumber.get(surahNumber);let sections=tahaviExplicitSections[surahNumber];if(!sections&&tahaviThirtyVerseSections.has(surahNumber)&&metadata){sections=[];for(let start=1;start<=metadata.ayahCount;start+=30)sections.push([start,Math.min(start+29,metadata.ayahCount)]);}if(!sections)return{url:surahUrl,surahUrl};const index=sections.findIndex(([start,end])=>ayah>=start&&ayah<=end);if(index<0)return{url:surahUrl,surahUrl};const [start,end]=sections[index];return{url:index===0?surahUrl:`${surahUrl}${index+1}/`,surahUrl,rangeLabel:`${start}–${end}`};}
function assemble(config:SourceLink,input:BuildSourceLinkInput):BuiltSourceLink{const work=sourceWorkById.get(config.sourceWorkId);const provider=sourceProviderById.get(config.providerId);const surah=surahMetadataByNumber.get(input.surahNumber);if(!work)throw new Error(`Kaynak eser bulunamadı: ${config.sourceWorkId}`);if(!provider)throw new Error(`Kaynak sağlayıcı bulunamadı: ${config.providerId}`);if(!provider.verified)throw new Error(`Kaynak sağlayıcı doğrulanmamış: ${provider.id}`);if(!surah)throw new Error(`Sure metadata bulunamadı: ${input.surahNumber}`);const slug=input.surahSlug??kuranMealiSlugOverrides[input.surahNumber]??surah.kuranVeMealiSlug;let url=provider.fallbackUrl;let surahFallbackUrl=provider.fallbackUrl;let rangeLabel:string|undefined;if(provider.strategy==="author-verse-page"){if(!config.authorSlug)throw new Error(`Müellif slug eksik: ${config.id}`);surahFallbackUrl=`${provider.baseUrl}/${config.authorSlug}/${slug}-suresi.htm`;url=`${provider.baseUrl}/${config.authorSlug}/${slug}-suresi-${input.ayahStart}.ayet.htm`;}else if(provider.strategy==="elmalili-ayah-page"){url=`https://islamarsivi.com/tefsir/tr-elmalili-hamdi-yazir/${input.surahNumber}/${input.ayahStart}/`;surahFallbackUrl=provider.fallbackUrl;}else if(provider.strategy==="tahavi-ayah-range"){const target=tahaviTarget(input.surahNumber,surah.kuranVeMealiSlug,input.ayahStart);url=target.url;surahFallbackUrl=target.surahUrl;rangeLabel=target.rangeLabel;}else if(provider.strategy==="direct-ayah-page"){const range=input.ayahEnd?`${input.ayahStart}-${input.ayahEnd}`:String(input.ayahStart);url=`${provider.baseUrl}/tefsir/${encodeURIComponent(surah.diyanetPathName)}-suresi/${getGlobalAyahNumber(input.surahNumber,input.ayahStart)}/${range}-ayet-tefsiri`;surahFallbackUrl=`${provider.baseUrl}/tefsir/sure/${input.surahNumber}`;}new URL(url);new URL(surahFallbackUrl);new URL(provider.fallbackUrl);return{id:config.id,work,provider,contentType:provider.contentType,url,surahFallbackUrl,generalFallbackUrl:provider.fallbackUrl,label:labels[provider.contentType],rangeLabel};}
export function buildSourceLink(input:BuildSourceLinkInput){const config=sourceLinks.find((item)=>{const provider=sourceProviderById.get(item.providerId);return item.sourceWorkId===input.sourceId&&provider?.contentType===input.contentType;});if(!config)throw new Error(`Kaynak aksiyonu bulunamadı: ${input.sourceId}/${input.contentType}`);return assemble(config,input);}
export function buildVerseSourceGroups(input:Omit<BuildSourceLinkInput,"sourceId"|"contentType">):BuiltSourceGroup[]{return sourceWorks.map((work)=>({work,actions:sourceLinks.filter((item)=>item.sourceWorkId===work.id).map((item)=>{const provider=sourceProviderById.get(item.providerId);if(!provider)throw new Error(`Provider bulunamadı: ${item.providerId}`);return buildSourceLink({...input,sourceId:work.id,contentType:provider.contentType});})}));}
export function testSourceLinkStrategy(config:SourceLink,input:Omit<BuildSourceLinkInput,"sourceId"|"contentType">){const provider=sourceProviderById.get(config.providerId);if(!provider)throw new Error(`Provider bulunamadı: ${config.providerId}`);return assemble(config,{...input,sourceId:config.sourceWorkId,contentType:provider.contentType});}
