import { taxonomyById } from "@/data/taxonomy";
import { topics } from "@/data/topics-v12";
import type { Topic } from "@/domain/content-types";
export type TopicSearchResult={topic:Topic;score:number};
const stopWords=new Set(["ve","veya","ile","bir","bu","da","de","icin","mi","mı","mu","mü","nasil","nasıl"]);
export function normalizeSearchText(value:string){return value.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[’'`]/g,"").replace(/ç/g,"c").replace(/ğ/g,"g").replace(/ı/g,"i").replace(/ö/g,"o").replace(/ş/g,"s").replace(/ü/g,"u").replace(/[^a-z0-9\s-]/g," ").replace(/\s+/g," ").trim();}
function match(query:string,field:string,exact:number,contains:number){const normalized=normalizeSearchText(field);if(query===normalized)return exact;if(normalized.includes(query)||query.includes(normalized))return contains;return 0;}
export function searchTopics(query:string,limit=5):TopicSearchResult[]{const normalizedQuery=normalizeSearchText(query);if(normalizedQuery.length<2)return[];const tokens=normalizedQuery.split(" ").filter((token)=>token.length>2&&!stopWords.has(token));return topics.map((topic)=>{let score=match(normalizedQuery,topic.title,1000,720);for(const alias of topic.aliases)score+=match(normalizedQuery,alias,800,560);for(const phrase of topic.searchPhrases)score+=match(normalizedQuery,phrase,600,420);for(const tag of topic.tags)score+=match(normalizedQuery,tag,400,280);for(const categoryId of topic.categories){const category=taxonomyById.get(categoryId);if(category)score+=match(normalizedQuery,category.title,200,140);}const searchable=normalizeSearchText([topic.title,topic.summary,...topic.aliases,...topic.searchPhrases,...topic.tags].join(" "));for(const token of tokens)if(searchable.includes(token))score+=token.length>=6?24:14;return{topic,score};}).filter((item)=>item.score>0).sort((a,b)=>b.score-a.score||a.topic.title.localeCompare(b.topic.title,"tr")).slice(0,limit);}
export function findTopic(query:string){return searchTopics(query,1)[0]?.topic;}
